# Create a program that reads a duration from the user as a number of days, hours, minutes, and seconds. Compute and display the total number of seconds represented by this duration.
print("\nSTART PROGRAM")
print("------------------")
print("\nHow many seconds have passed?")
print("\nDays")
days = int(input())
print("\nHours")
hours = int(input())
print("\nMinutes")
minutes = int(input())
print("\nSeconds")
seconds = int(input())
print("\nHave passed...")
print(str(seconds + (minutes * 60) + (hours * 60 * 60) + (days * 24 * 60 * 60))+" seconds")