print ("Questo programma calcola l'area di un stanza in metri.")
larghezza = input("Inserisci la larghezza col numero decimale ")
lunghezza = input("inserisci la lunghezza col numero decimale ")
risultato = float(larghezza) * float(lunghezza)
print (risultato)