print ("ti stavi chiedendo come combattere l'inquinamento globale e allo stesso tempo creare un guadagno da questo?")
print ("Io sono la soluzione hai tuoi problemi! Mi presento sono bottleDeposits!")
print ("Per ogni bottiglia vuota che mi regalerai per te ci sarà un compenso in base alla sua capacità.")
print ("Inserisci il numero di bottiglie che mi hai regalato con capacità da un litro o inferiore:")
bot1 = int(input())
print ("Inserisci il numero di bottiglie che mi hai regalato con capacità superiore ad un litro:")
bot2 = int(input())
print ("Amazing! Hai guadagnato la bellezza di:")
cash = float((bot1 * 0.10) + (bot2 * 0.25))
round (cash, 2)
print (str(cash) + ("$!"))